# Generated by Django 6.0.5 on 2026-05-27 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_add_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='data.person'),
        ),
    ]
