# Generated by Django 6.0.5 on 2026-05-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_add_person_to_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=20)),
                ('group_key', models.CharField(max_length=64)),
                ('rank', models.CharField(max_length=128)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderings', to='data.task')),
            ],
            options={
                'indexes': [models.Index(fields=['dimension', 'group_key', 'rank'], name='data_taskor_dimensi_81ee7d_idx')],
                'unique_together': {('task', 'dimension', 'group_key')},
            },
        ),
    ]
