# Generated by Django 6.0.5 on 2026-05-31 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_taskorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
