# Generated by Django 6.0.5 on 2026-06-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_project_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="status",
        ),
        migrations.DeleteModel(
            name="TaskOrder",
        ),
    ]
