# Generated by Django 6.0.5 on 2026-07-12 10:57

import data.models.project
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_task_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teams_notify_events',
            field=models.JSONField(blank=True, default=data.models.project.default_teams_notify_events),
        ),
        migrations.AddField(
            model_name='project',
            name='teams_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
