# Generated by Django 6.0.5 on 2026-09-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_project_teams_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="responsible_people",
            field=models.ManyToManyField(
                blank=True, related_name="responsible_projects", to="data.person"
            ),
        ),
    ]
