# Generated by Django 6.0.5 on 2026-09-29 23:01

import data.models.project
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_milestone_require_move_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='teams_upn',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='workspace',
            name='teams_notify_events',
            field=models.JSONField(blank=True, default=data.models.project.default_teams_notify_events),
        ),
        migrations.AddField(
            model_name='workspace',
            name='teams_webhook_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.CreateModel(
            name='ProjectSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='data.membership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='data.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'membership'), name='unique_project_subscription')],
            },
        ),
        migrations.CreateModel(
            name='TeamsDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_deliveries', to='data.workspace')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='data_teamsd_status_58dc5b_idx')],
            },
        ),
    ]
