# Generated by Django 6.0.5 on 2026-09-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_migrate_workspace_teams_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
