# Generated by Django 6.0.5 on 2026-10-01 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0022_milestone_is_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='teams_public_subscriber_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='PublicProjectSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_key_hash', models.CharField(db_index=True, max_length=64)),
                ('teams_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_subscriptions', to='data.project')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'browser_key_hash'), name='unique_public_project_subscription')],
            },
        ),
    ]
